### ISSUE TITLE
[Bug Report]: NestJS, watch mode don't close previuos server instance

### ISSUE THREAD

**Issue by Altro31** [farm-fe/farm#1643] opened 2024-07-19 05:49 UTC
### Steps to reproduce

1. Run in watch mode
`bun run dev`
2. Do any change. Example: change getHello function. Then, watch modes should restart the server
3. Repeat step 2
4. Now, there is an error saying that there is something running on port 3000.

![image](https://github.com/user-attachments/assets/6fb80e60-2077-4150-950f-9ab827961096)

### Reproduce link
https://github.com/Altro31/farm-project.git

### What is actually happening?

Watch mode, when NestJS app is running, don't close the previous server instance

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 AMD Athlon 200GE with Radeon Vega Graphics
    Memory: 8.86 GB / 21.92 GB
  Binaries:
    Node: 22.0.0 - D:\Dev\nodejs\node.EXE
    npm: 10.6.0 - D:\Dev\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.20 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
```

**Comment by fu050409** [comment] 2024-07-19 06:17
We'll take a look

**Comment by ErKeLost** [comment] 2024-07-19 07:18
@Altro31  I used bun and did not reproduce your problem. Are you using the latest version of farm/core?

**Comment by Altro31** [comment] 2024-07-19 07:42
1.3.0

**Comment by Altro31** [comment] 2024-07-19 07:53
Actually, i updated to v1.3.6, also create a new project and I still getting the same issue

**Comment by fu050409** [comment] 2024-07-19 08:00
> Actually, i updated to v1.3.6, also create a new project and I still getting the same issue

> Actually, i updated to v1.3.6, also create a new project and I still getting the same issue

Could you please create an exmaple repository which can reproduce this issue to help use locate this issue?

**Comment by Altro31** [comment] 2024-07-19 08:54
> > Actually, i updated to v1.3.6, also create a new project and I still getting the same issue
> 
> Could you please create an exmaple repository which can reproduce this issue to help use locate this issue? I can't reproduce the problem consistently.

https://github.com/Altro31/farm-project.git

**Comment by ErKeLost** [comment] 2024-07-19 09:58
This may be a farmup bug. I'll fix it.

**Comment by ErKeLost** [comment] 2024-07-21 11:47
Hello, @Altro31  installing the latest farmup version should solve your problem. The reason is that the previous child process has not been killed but the next child process has been opened, causing a port conflict.

**Comment by ErKeLost** [comment] 2024-07-22 02:26
If the problem is solved, I will close this issue first.

**Closed by ErKeLost** 2024-07-22 02:26 UTC
