### ISSUE TITLE
Vue SFC Src CSS Support

### ISSUE THREAD

**Issue by skywalker512** [farm-fe/farm#952] opened 2024-02-04 07:33 UTC
### Steps to reproduce

Writing a Vue SFC component and using src css will encounter a series of problems.
```vue
<style scoped src="./app.css"></style>
```
- ` Failed to start the server: Error: Cannot read properties of undefined (reading 'custom')`
   - I modified `@farmfe+core@0.16.4/node_modules/@farmfe/core/dist/plugin/js/farm-to-vite-context.js:90:25`
   - It should be because the linkSrcToDescriptor function in vitejs+plugin-vue@5.0.3 did not pass the third optional parameter when calling pluginContext.resolve.
- After solving the above problem, it will lead to other problems.
- `Failed to start the server: Error: Can not load ./app.css?vue&type=style&index=1&src=7a7a37b1&scoped=7a7a37b1&lang.css`
  - I found that the import inside the transform hook does not seem to be handled correctly.
 
Below is the test plugin code I wrote.
```js
const a: JsPlugin = {
  name: 'a',
  transform: {
    filters: {
      resolvedPaths: ['a.ts'],
    },
    executor(param, context, hookContext) {
      console.log(param, context, hookContext);
      return {
        content: `import './style.scss?q=2&c=3';`,
        moduleType: 'js',
      };
    },
  },
};
```

### What is expected?

N/A

### What is actually happening?

N/A

### System Info

```Shell
Irrelevant system
```

**Comment by wre232114** [comment] 2024-02-04 08:06
Could you provide a repository that can reproduce this issue. It seems that there are a series of problems, we may need to find out which part is unsupported in Farm

**Comment by skywalker512** [comment] 2024-02-04 08:30
https://github.com/skywalker512/farm-vue-sfc-reproduce

@wre232114

**Comment by wre232114** [comment] 2024-02-04 08:34
Thanks, I'll take a look

**Comment by skywalker512** [comment] 2024-02-04 08:43
> I found that the import inside the transform hook does not seem to be handled correctly.

I feel like I made a mistake here, it seems that adding vue might cause some issues.

https://github.com/skywalker512/farm-vue-sfc-reproduce/commit/2f65d732b78d888d15aef15decdffb34107559fa#diff-f4b0dd1e965356e58d87d876dc43e4fc428f2480645a41c2049717d1327d4fa3

```diff
- code: `import './style.css?type=style&index=0&src=7a7a37b1&scoped=7a7a37b1&lang.css'`,
+ code: `import './style.css?vue&type=style&index=0&src=7a7a37b1&scoped=7a7a37b1&lang.css'`,
```

**Comment by wre232114** [comment] 2024-02-04 23:56
I reproduced this issue in the repo. I'll fix it today

**Comment by wre232114** [comment] 2024-02-05 00:39
```js
import './style.css?vue&type=style&index=0&src=7a7a37b1&scoped=7a7a37b1&lang.css'
```
is not supported by `@vitejs/plugin-vue`, because it implement `resolveId` hook:
```js
// @vitejs/plugin-vue
async resolveId(id) {
      // ...
      if (parseVueRequest(id).query.vue) {
        return id;
      }
    }
```
which will return `'./style.css?vue&type=style&index=0&src=7a7a37b1&scoped=7a7a37b1&lang.css'` directly, instead of a expected absolute path.

So I think you should change your plugin implementation to:
```js
const b: Plugin = {
  name: 'b',
  transform(code, id, options) {
    if (id.includes('a.ts')) {
      const dir = path.dirname(id);
      const resolvedPath = path.resolve(dir, 'style.css').replaceAll('\\', '\\\\');
      return {
        // code: `import './style.css?type=style&index=0&src=7a7a37b1&scoped=7a7a37b1&lang.css'`,
        code: `import '${resolvedPath}?vue&type=style&index=0&src=7a7a37b1&scoped=7a7a37b1&lang.css'`,
      };
    }
  },
};
```
Above code would work fine. @skywalker512

**Comment by wre232114** [comment] 2024-02-05 00:50
Bug there are 2 bugs in Farm indeed, it will be fixed in `0.16.5` today

**Comment by skywalker512** [comment] 2024-02-05 01:16
> So I think you should change your plugin implementation to:

Thank you very much for your answer. I don't want to implement related plugins, I just want to indicate how the Vue Vite plugin handles CSS src.

**Comment by wre232114** [comment] 2024-02-05 01:43
vue vite plugin returns `./style.css?vue&xxxx` for css src. but it return `/src/style.css?vue&xxx` in dev, it's inconsistent. Anyway, Farm will try to be compatible with this behavior to make `css src` work as expected.

**Closed** 2024-02-05 08:56 UTC
Labels: bug, adapter vite plugins

**Comment by wre232114** [comment] 2024-02-05 10:13
supported in `@farmfe/core@0.16.5`
