### ISSUE TITLE
[Bug Report]: yarn create-farm not found

### ISSUE THREAD

**Issue by blaicer15** [farm-fe/farm#1631] opened 2024-07-17 15:46 UTC
### Steps to reproduce

After executing the command:

yarn create farm@latest

installs the framework but when trying to use it it gives the following error:

![imagen](https://github.com/user-attachments/assets/5a25174e-1d6a-4d00-a2c6-8cc2fee89b62)

### What is actually happening?

Can't create project using yarn

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.3 (Virginia)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 3.52 GB / 7.71 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 126.0.6478.182
  npmPackages:
    @farmfe/core: ^1.3.0 => 1.3.3
```

**Comment by fu050409** [comment] 2024-07-18 02:51
Use `yarn create farm` instead.

**Comment by fu050409** [comment] 2024-07-18 04:52
Hi, I tried `yarn create farm@latest` on my local machine and it worked:

![45ec1404b74b3be2259dc92e72cf81a2](https://github.com/user-attachments/assets/705ed5a9-5181-44da-8798-e1d5c5653c7f)

I found that it seems you're using `yarn@1.22.22`, maybe you should try to upgrade your yarn to the latest version. I think this is not a bug of `farm` so I'll close this issue. Feel free to comment here later if more issues happened :)

**Closed by fu050409** 2024-07-18 04:52 UTC

**Comment by blaicer15** [comment] 2024-07-18 17:48
You are right, but there was a problem that I encountered when trying to update the version of Yarn.

We intentionally **_don't release modern releases on the npm yarn package_**, so as not to break older projects which didn't migrate yet.

Complete information: [https://yarnpkg.com/blog/release/4.0#installing-yarn](url)

To update to the latest version of YARN, use the script I found: [https://gist.github.com/wojtekmaj/c38351dd715c1b108ab1ab089fcaf6fc](url)

Avoiding the "git add..." part, everything worked perfectly. **Thank you**
