### ISSUE TITLE
在js插件中写babel.transfromSync报错

### ISSUE THREAD

**Issue by ysy945** [farm-fe/farm#254] opened 2023-04-23 16:53 UTC
### Steps to reproduce

- farm.config.ts
```js
import { defineFarmConfig } from "@farmfe/core/dist/config";
import { transformSync } from "@babel/core";

export default defineFarmConfig({
  compilation: {
    input: {
      index: "./index.html",
    },
    output: {
      path: "./build",
    },
  },
  plugins: [
    {
      name: "test-bug",
      load: {
        filters: {
          resolvedPaths: [".*"],
        },
        executor(params) {
          console.log(111);
          try {
            transformSync("const a = 1");
          } catch (err) {
            console.log(err);
          }

          return {
            content: "",
            moduleType: "js",
          };
        },
      },
    },
  ],
});

```

### What is expected?

- no errors

### What is actually happening?

<img width="985" alt="image" src="https://user-images.githubusercontent.com/79794654/233853345-884de499-ee52-4c4a-bc6c-fad67898ae62.png">

### System Info

```Shell
@fareme/core: "^0.6.4"
```

**Comment by oblador** [comment] 2023-04-24 07:09
Duplicate of https://github.com/farm-fe/farm/issues/248

**Closed** 2023-04-24 15:25 UTC
Labels: bug
